### PR TITLE
Fix for - New node is not able to join cluster

### LINKED ISSUE #39: New node is not able to join cluster
A new node fails to join the cluster .
Steps to replicate
- start a 3 node redis repl nexus cluster
- put more than 100 entries in the cluster. (100 entries will be sufficient to create snapshots since we give --nexus-snapshot-count 100 in ProcFile)
- try to add another node

### PR DESCRIPTION
**Pull request by sandboxo**
Fixes #39

### CODE REVIEW

File: internal/raft/node.go [hunk 1]
```diff
@@ -463,7 +463,7 @@ func (rc *raftNode) triggerSnapshot() {
 	}
 	defer data.Close()
 
-	snapshot, err := rc.raftStorage.CreateSnapshot(rc.appliedIndex, &rc.confState, nil)
+	snapshot, err := rc.raftStorage.CreateSnapshot(appliedIndex, &rc.confState, nil)
```
Comment (kingster) [inline internal/raft/node.go:466]: Nice catch.
